export const permissions = {
  organizationsRead: 'organizations.read',
  dashboardRead: 'dashboard.read',
  salesOrdersRead: 'sales-orders.read',
  purchaseOrdersRead: 'purchase-orders.read',
  organizationsUpdate: 'organizations.update',
  customersRead: 'customers.read',
  customersCreate: 'customers.create',
  suppliersRead: 'suppliers.read',
  suppliersCreate: 'suppliers.create',
  productsRead: 'products.read',
  productsCreate: 'products.create',
  inventoryRead: 'inventory.read',
  inventoryAdjust: 'inventory.adjust',
  warehousesRead: 'warehouses.read',
  warehousesCreate: 'warehouses.create',
  purchaseRequestsRead: 'purchase-requests.read',
  purchaseRequestsCreate: 'purchase-requests.create',
  purchaseRequestsApprove: 'purchase-requests.approve',
  purchaseOrdersCreate: 'purchase-orders.create',
  purchaseOrdersReceive: 'purchase-orders.receive',
  salesOrdersCreate: 'sales-orders.create',
  salesOrdersConfirm: 'sales-orders.confirm',
  salesOrdersCancel: 'sales-orders.cancel',
  invoicesRead: 'invoices.read',
  invoicesCreate: 'invoices.create',
  invoicesIssue: 'invoices.issue',
  paymentsRead: 'payments.read',
  paymentsCreate: 'payments.create',
  supplierInvoicesRead: 'supplier-invoices.read',
  supplierInvoicesCreate: 'supplier-invoices.create',
  supplierPaymentsRead: 'supplier-payments.read',
  supplierPaymentsCreate: 'supplier-payments.create',
  accountingRead: 'accounting.read',
  accountingPost: 'accounting.post',
  workflowsExecute: 'workflows.execute',
  branchesRead: 'branches.read',
  branchesCreate: 'branches.create',
  catalogsRead: 'catalogs.read',
  catalogsCreate: 'catalogs.create',
  crmRead: 'crm.read',
  crmCreate: 'crm.create',
  shipmentsCreate: 'shipments.create',
  shipmentsDispatch: 'shipments.dispatch',
  shipmentsCancel: 'shipments.cancel',
  shipmentsDeliver: 'shipments.deliver',
} as const;

export type Permission = (typeof permissions)[keyof typeof permissions];

const rolePermissions: Record<string, readonly Permission[]> = {
  admin: Object.values(permissions),
  user: [permissions.organizationsRead, permissions.dashboardRead, permissions.customersRead, permissions.suppliersRead, permissions.productsRead, permissions.inventoryRead, permissions.warehousesRead, permissions.purchaseRequestsRead],
};

export const roleHasPermission = (roles: readonly string[], permission: Permission): boolean =>
  roles.some((role) => rolePermissions[role]?.includes(permission) ?? false);
