export const permissions = {
  organizationsRead: 'organizations.read',
  dashboardRead: 'dashboard.read',
  salesOrdersRead: 'sales-orders.read',
  purchaseOrdersRead: 'purchase-orders.read',
  organizationsUpdate: 'organizations.update',
  usersRead: 'users.read',
  usersCreate: 'users.create',
  usersUpdate: 'users.update',
  customersRead: 'customers.read',
  customersCreate: 'customers.create',
  customersUpdate: 'customers.update',
  suppliersRead: 'suppliers.read',
  suppliersCreate: 'suppliers.create',
  suppliersUpdate: 'suppliers.update',
  productsRead: 'products.read',
  productsCreate: 'products.create',
  productsUpdate: 'products.update',
  inventoryRead: 'inventory.read',
  inventoryAdjust: 'inventory.adjust',
  warehousesRead: 'warehouses.read',
  warehousesCreate: 'warehouses.create',
  warehousesUpdate: 'warehouses.update',
  purchaseRequestsRead: 'purchase-requests.read',
  purchaseRequestsCreate: 'purchase-requests.create',
  purchaseRequestsApprove: 'purchase-requests.approve',
  purchaseOrdersCreate: 'purchase-orders.create',
  purchaseOrdersSend: 'purchase-orders.send',
  purchaseOrdersReceive: 'purchase-orders.receive',
  salesOrdersCreate: 'sales-orders.create',
  salesOrdersConfirm: 'sales-orders.confirm',
  salesOrdersCancel: 'sales-orders.cancel',
  invoicesRead: 'invoices.read',
  invoicesCreate: 'invoices.create',
  invoicesIssue: 'invoices.issue',
  creditMemosRead: 'credit-memos.read',
  creditMemosCreate: 'credit-memos.create',
  customerRefundsRead: 'customer-refunds.read',
  customerRefundsCreate: 'customer-refunds.create',
  paymentsRead: 'payments.read',
  paymentsCreate: 'payments.create',
  supplierInvoicesRead: 'supplier-invoices.read',
  supplierInvoicesCreate: 'supplier-invoices.create',
  supplierPaymentsRead: 'supplier-payments.read',
  supplierPaymentsCreate: 'supplier-payments.create',
  accountingRead: 'accounting.read',
  accountingPost: 'accounting.post',
  workflowsExecute: 'workflows.execute',
  branchesRead: 'branches.read',
  branchesCreate: 'branches.create',
  branchesUpdate: 'branches.update',
  catalogsRead: 'catalogs.read',
  catalogsCreate: 'catalogs.create',
  catalogsUpdate: 'catalogs.update',
  crmRead: 'crm.read',
  crmCreate: 'crm.create',
  crmUpdate: 'crm.update',
  shipmentsCreate: 'shipments.create',
  shipmentsRead: 'shipments.read',
  shipmentsDispatch: 'shipments.dispatch',
  shipmentsCancel: 'shipments.cancel',
  shipmentsDeliver: 'shipments.deliver',
} as const;

export type Permission = (typeof permissions)[keyof typeof permissions];

const rolePermissions: Record<string, readonly Permission[]> = {
  admin: Object.values(permissions),
  user: [permissions.organizationsRead, permissions.dashboardRead, permissions.customersRead, permissions.suppliersRead, permissions.productsRead, permissions.inventoryRead, permissions.warehousesRead, permissions.purchaseRequestsRead],
};

export const roleHasPermission = (roles: readonly string[], permission: Permission): boolean =>
  roles.some((role) => rolePermissions[role]?.includes(permission) ?? false);
