export const permissions = {
  organizationsRead: 'organizations.read',
  dashboardRead: 'dashboard.read',
  salesOrdersRead: 'sales-orders.read',
  purchaseOrdersRead: 'purchase-orders.read',
  organizationsUpdate: 'organizations.update',
  usersRead: 'users.read',
  usersCreate: 'users.create',
  usersUpdate: 'users.update',
  customersRead: 'customers.read',
  customersCreate: 'customers.create',
  customersUpdate: 'customers.update',
  suppliersRead: 'suppliers.read',
  suppliersCreate: 'suppliers.create',
  suppliersUpdate: 'suppliers.update',
  productsRead: 'products.read',
  productsCreate: 'products.create',
  productsUpdate: 'products.update',
  inventoryRead: 'inventory.read',
  inventoryAdjust: 'inventory.adjust',
  warehousesRead: 'warehouses.read',
  warehousesCreate: 'warehouses.create',
  warehousesUpdate: 'warehouses.update',
  purchaseRequestsRead: 'purchase-requests.read',
  purchaseRequestsCreate: 'purchase-requests.create',
  purchaseRequestsApprove: 'purchase-requests.approve',
  purchaseOrdersCreate: 'purchase-orders.create',
  purchaseOrdersSend: 'purchase-orders.send',
  purchaseOrdersReceive: 'purchase-orders.receive',
  salesOrdersCreate: 'sales-orders.create',
  salesOrdersConfirm: 'sales-orders.confirm',
  salesOrdersCancel: 'sales-orders.cancel',
  invoicesRead: 'invoices.read',
  invoicesCreate: 'invoices.create',
  invoicesIssue: 'invoices.issue',
  creditMemosRead: 'credit-memos.read',
  creditMemosCreate: 'credit-memos.create',
  customerRefundsRead: 'customer-refunds.read',
  customerRefundsCreate: 'customer-refunds.create',
  paymentsRead: 'payments.read',
  paymentsCreate: 'payments.create',
  supplierInvoicesRead: 'supplier-invoices.read',
  supplierInvoicesCreate: 'supplier-invoices.create',
  supplierPaymentsRead: 'supplier-payments.read',
  supplierPaymentsCreate: 'supplier-payments.create',
  accountingRead: 'accounting.read',
  accountingPost: 'accounting.post',
  workflowsExecute: 'workflows.execute',
  branchesRead: 'branches.read',
  branchesCreate: 'branches.create',
  branchesUpdate: 'branches.update',
  catalogsRead: 'catalogs.read',
  catalogsCreate: 'catalogs.create',
  catalogsUpdate: 'catalogs.update',
  crmRead: 'crm.read',
  crmCreate: 'crm.create',
  crmUpdate: 'crm.update',
  shipmentsCreate: 'shipments.create',
  shipmentsRead: 'shipments.read',
  shipmentsDispatch: 'shipments.dispatch',
  shipmentsCancel: 'shipments.cancel',
  shipmentsDeliver: 'shipments.deliver',
  // Settings
  settingsRead: 'settings.read',
  settingsCreate: 'settings.create',
  settingsUpdate: 'settings.update',
  settingsDelete: 'settings.delete',
  // Taxes
  taxesRead: 'taxes.read',
  taxesCreate: 'taxes.create',
  taxesUpdate: 'taxes.update',
  taxesDelete: 'taxes.delete',
  // Quotations
  quotationsRead: 'quotations.read',
  quotationsCreate: 'quotations.create',
  quotationsUpdate: 'quotations.update',
  quotationsDelete: 'quotations.delete',
  quotationsConvert: 'quotations.convert',
  // Returns
  returnsRead: 'returns.read',
  returnsCreate: 'returns.create',
  returnsProcess: 'returns.process',
  // Lots & Serial Numbers
  lotsRead: 'lots.read',
  lotsCreate: 'lots.create',
  lotsUpdate: 'lots.update',
  serialNumbersRead: 'serial-numbers.read',
  serialNumbersCreate: 'serial-numbers.create',
  serialNumbersUpdate: 'serial-numbers.update',
  // Chart of Accounts
  chartOfAccountsRead: 'chart-of-accounts.read',
  chartOfAccountsCreate: 'chart-of-accounts.create',
  chartOfAccountsUpdate: 'chart-of-accounts.update',
  chartOfAccountsDelete: 'chart-of-accounts.delete',
  // Journal Entries
  journalEntriesRead: 'journal-entries.read',
  journalEntriesCreate: 'journal-entries.create',
  journalEntriesUpdate: 'journal-entries.update',
  journalEntriesPost: 'journal-entries.post',
  journalEntriesReverse: 'journal-entries.reverse',
  // Accounts Receivable / Payable
  accountsReceivableRead: 'accounts-receivable.read',
  accountsReceivableManage: 'accounts-receivable.manage',
  accountsPayableRead: 'accounts-payable.read',
  accountsPayableManage: 'accounts-payable.manage',
  // Banking
  bankingRead: 'banking.read',
  bankingManage: 'banking.manage',
  bankingReconcile: 'banking.reconcile',
  // Budgets
  budgetsRead: 'budgets.read',
  budgetsCreate: 'budgets.create',
  budgetsUpdate: 'budgets.update',
  budgetsApprove: 'budgets.approve',
  budgetsDelete: 'budgets.delete',
  // Manufacturing
  billsOfMaterialsRead: 'bills-of-materials.read',
  billsOfMaterialsCreate: 'bills-of-materials.create',
  billsOfMaterialsUpdate: 'bills-of-materials.update',
  billsOfMaterialsDelete: 'bills-of-materials.delete',
  productionOrdersRead: 'production-orders.read',
  productionOrdersCreate: 'production-orders.create',
  productionOrdersUpdate: 'production-orders.update',
  productionOrdersStart: 'production-orders.start',
  productionOrdersComplete: 'production-orders.complete',
  mrpRead: 'mrp.read',
  mrpRun: 'mrp.run',
  workCentersRead: 'work-centers.read',
  workCentersCreate: 'work-centers.create',
  workCentersUpdate: 'work-centers.update',
  materialsRead: 'materials.read',
  materialsConsume: 'materials.consume',
  // Logistics
  carriersRead: 'carriers.read',
  carriersCreate: 'carriers.create',
  carriersUpdate: 'carriers.update',
  routesRead: 'routes.read',
  routesCreate: 'routes.create',
  routesUpdate: 'routes.update',
  deliveriesRead: 'deliveries.read',
  deliveriesCreate: 'deliveries.create',
  deliveriesUpdate: 'deliveries.update',
  // Projects
  projectsRead: 'projects.read',
  projectsCreate: 'projects.create',
  projectsUpdate: 'projects.update',
  projectsManage: 'projects.manage',
  tasksRead: 'tasks.read',
  tasksCreate: 'tasks.create',
  tasksUpdate: 'tasks.update',
  timeTrackingRead: 'time-tracking.read',
  timeTrackingCreate: 'time-tracking.create',
  timeTrackingApprove: 'time-tracking.approve',
  // Services
  ticketsRead: 'tickets.read',
  ticketsCreate: 'tickets.create',
  ticketsAssign: 'tickets.assign',
  ticketsResolve: 'tickets.resolve',
  serviceOrdersRead: 'service-orders.read',
  serviceOrdersCreate: 'service-orders.create',
  serviceOrdersUpdate: 'service-orders.update',
  slaRead: 'sla.read',
  slaManage: 'sla.manage',
  // Documents
  documentsRead: 'documents.read',
  documentsCreate: 'documents.create',
  documentsUpdate: 'documents.update',
  attachmentsRead: 'attachments.read',
  attachmentsCreate: 'attachments.create',
  contractsRead: 'contracts.read',
  contractsCreate: 'contracts.create',
  contractsSign: 'contracts.sign',
  // Reports & Analytics
  reportsRead: 'reports.read',
  reportsCreate: 'reports.create',
  reportsExport: 'reports.export',
  dashboardsRead: 'dashboards.read',
  dashboardsCreate: 'dashboards.create',
  dashboardsManage: 'dashboards.manage',
  analyticsRead: 'analytics.read',
  // Automation
  workflowExecutionsRead: 'workflow-executions.read',
  workflowExecutionsManage: 'workflow-executions.manage',
  workflowTasksRead: 'workflow-tasks.read',
  workflowTasksManage: 'workflow-tasks.manage',
  notificationsRead: 'notifications.read',
  notificationsSend: 'notifications.send',
  notificationsManage: 'notifications.manage',
  // Integrations
  integrationsRead: 'integrations.read',
  integrationsManage: 'integrations.manage',
  webhooksRead: 'webhooks.read',
  webhooksManage: 'webhooks.manage',
  apiKeysRead: 'api-keys.read',
  apiKeysManage: 'api-keys.manage',
  externalServicesRead: 'external-services.read',
  externalServicesManage: 'external-services.manage',
  // AI
  assistantRead: 'assistant.read',
  assistantUse: 'assistant.use',
  forecastingRead: 'forecasting.read',
  forecastingRun: 'forecasting.run',
  anomalyDetectionRead: 'anomaly-detection.read',
  anomalyDetectionRun: 'anomaly-detection.run',
  documentAnalysisRead: 'document-analysis.read',
  documentAnalysisRun: 'document-analysis.run',
  recommendationsRead: 'recommendations.read',
  recommendationsRun: 'recommendations.run',
  agentsRead: 'agents.read',
  agentsManage: 'agents.manage',
} as const;

export type Permission = (typeof permissions)[keyof typeof permissions];

const rolePermissions: Record<string, readonly Permission[]> = {
  admin: Object.values(permissions),
  user: [
    permissions.organizationsRead,
    permissions.dashboardRead,
    permissions.customersRead,
    permissions.suppliersRead,
    permissions.productsRead,
    permissions.inventoryRead,
    permissions.warehousesRead,
    permissions.purchaseRequestsRead,
    permissions.salesOrdersRead,
    permissions.purchaseOrdersRead,
    permissions.invoicesRead,
    permissions.paymentsRead,
    permissions.accountingRead,
    permissions.branchesRead,
    permissions.catalogsRead,
    permissions.crmRead,
    permissions.shipmentsRead,
    permissions.settingsRead,
    permissions.taxesRead,
    permissions.quotationsRead,
    permissions.returnsRead,
    permissions.lotsRead,
    permissions.serialNumbersRead,
    permissions.chartOfAccountsRead,
    permissions.journalEntriesRead,
    permissions.accountsReceivableRead,
    permissions.accountsPayableRead,
    permissions.bankingRead,
    permissions.budgetsRead,
    permissions.billsOfMaterialsRead,
    permissions.productionOrdersRead,
    permissions.mrpRead,
    permissions.workCentersRead,
    permissions.materialsRead,
    permissions.carriersRead,
    permissions.routesRead,
    permissions.deliveriesRead,
    permissions.projectsRead,
    permissions.tasksRead,
    permissions.timeTrackingRead,
    permissions.ticketsRead,
    permissions.serviceOrdersRead,
    permissions.slaRead,
    permissions.documentsRead,
    permissions.attachmentsRead,
    permissions.contractsRead,
    permissions.reportsRead,
    permissions.dashboardsRead,
    permissions.analyticsRead,
    permissions.workflowExecutionsRead,
    permissions.workflowTasksRead,
    permissions.notificationsRead,
    permissions.integrationsRead,
    permissions.webhooksRead,
    permissions.apiKeysRead,
    permissions.externalServicesRead,
    permissions.assistantRead,
    permissions.forecastingRead,
    permissions.anomalyDetectionRead,
    permissions.documentAnalysisRead,
    permissions.recommendationsRead,
    permissions.agentsRead,
  ],
};

export const roleHasPermission = (roles: readonly string[], permission: Permission): boolean =>
  roles.some((role) => rolePermissions[role]?.includes(permission) ?? false);
