/**
 * SYNTARA ERP Design System - Button Component
 */

import React, { forwardRef, ReactNode } from 'react';
import { Pressable, Text, View, ViewStyle, TextStyle, StyleProp, ActivityIndicator } from 'react-native';
import { useTheme } from '../hooks';

export type ButtonVariant = 'primary' | 'accent' | 'secondary' | 'ghost' | 'danger' | 'success' | 'warning';
export type ButtonSize = 'sm' | 'md' | 'lg' | 'xl';

export interface ButtonProps { children?: ReactNode; variant?: ButtonVariant; size?: ButtonSize; fullWidth?: boolean; disabled?: boolean; loading?: boolean; loadingText?: string; leftIcon?: ReactNode; rightIcon?: ReactNode; iconOnly?: boolean; onPress?: () => void; onLongPress?: () => void; style?: StyleProp<ViewStyle>; textStyle?: StyleProp<TextStyle>; iconStyle?: StyleProp<ViewStyle>; testID?: string; accessibilityLabel?: string; accessibilityHint?: string; type?: 'button' | 'submit' | 'reset'; preventDefault?: boolean; }

const variantStyles: Record<ButtonVariant, { bg: string; bgHover: string; bgPressed: string; bgDisabled: string; borderColor: string; textColor: string; textColorDisabled: string; shadow: string; shadowHover: string }> = { primary: { bg: '{colors.brand.blue}', bgHover: '{colors.brand.blueDark}', bgPressed: '{colors.brand.blueDark}', bgDisabled: '{colors.border.primary}', borderColor: 'transparent', textColor: '{colors.text.onBrand}', textColorDisabled: '{colors.text.muted}', shadow: 'blue.sm', shadowHover: 'blue.md' }, accent: { bg: '{colors.brand.cyan}', bgHover: '{colors.brand.cyanHover}', bgPressed: '{colors.brand.cyan}', bgDisabled: '{colors.border.primary}', borderColor: 'transparent', textColor: '{colors.text.onBrand}', textColorDisabled: '{colors.text.muted}', shadow: 'cyan.sm', shadowHover: 'cyan.md' }, secondary: { bg: 'transparent', bgHover: '{colors.surface.hover}', bgPressed: '{colors.surface.pressed}', bgDisabled: 'transparent', borderColor: '{colors.border.primary}', textColor: '{colors.text.primary}', textColorDisabled: '{colors.text.muted}', shadow: 'none', shadowHover: 'none' }, ghost: { bg: 'transparent', bgHover: '{colors.surface.hover}', bgPressed: '{colors.surface.pressed}', bgDisabled: 'transparent', borderColor: 'transparent', textColor: '{colors.text.primary}', textColorDisabled: '{colors.text.muted}', shadow: 'none', shadowHover: 'none' }, danger: { bg: '{colors.semantic.error.main}', bgHover: '{colors.semantic.error.dark}', bgPressed: '{colors.semantic.error.dark}', bgDisabled: '{colors.border.primary}', borderColor: 'transparent', textColor: '{colors.semantic.error.onError}', textColorDisabled: '{colors.text.muted}', shadow: 'error.sm', shadowHover: 'error.md' }, success: { bg: '{colors.semantic.success.main}', bgHover: '{colors.semantic.success.dark}', bgPressed: '{colors.semantic.success.dark}', bgDisabled: '{colors.border.primary}', borderColor: 'transparent', textColor: '{colors.semantic.success.onSuccess}', textColorDisabled: '{colors.text.muted}', shadow: 'success.sm', shadowHover: 'success.md' }, warning: { bg: '{colors.semantic.warning.main}', bgHover: '{colors.semantic.warning.dark}', bgPressed: '{colors.semantic.warning.dark}', bgDisabled: '{colors.border.primary}', borderColor: 'transparent', textColor: '{colors.semantic.warning.onWarning}', textColorDisabled: '{colors.text.muted}', shadow: 'warning.sm', shadowHover: 'warning.md' } };

const sizeStyles: Record<ButtonSize, { height: number; paddingHorizontal: number; paddingVertical: number; fontSize: number; iconSize: number; iconGap: number; minWidth: number; borderRadius: number }> = { sm: { height: 32, paddingHorizontal: 12, paddingVertical: 6, fontSize: 12, iconSize: 14, iconGap: 6, minWidth: 64, borderRadius: 6 }, md: { height: 40, paddingHorizontal: 16, paddingVertical: 10, fontSize: 14, iconSize: 16, iconGap: 8, minWidth: 80, borderRadius: 8 }, lg: { height: 48, paddingHorizontal: 20, paddingVertical: 12, fontSize: 16, iconSize: 18, iconGap: 10, minWidth: 96, borderRadius: 10 }, xl: { height: 56, paddingHorizontal: 24, paddingVertical: 14, fontSize: 18, iconSize: 20, iconGap: 12, minWidth: 120, borderRadius: 12 } };

const Button = forwardRef<any, ButtonProps>(({ children, variant = 'primary', size = 'md', fullWidth = false, disabled = false, loading = false, loadingText, leftIcon, rightIcon, iconOnly = false, onPress, onLongPress, style, textStyle, iconStyle, testID, accessibilityLabel, accessibilityHint, type = 'button', preventDefault = true }, ref) => {
  const { theme } = useTheme(); const colors = theme.colors;
  const vStyles = variantStyles[variant]; const sStyles = sizeStyles[size]; const isInteractive = !disabled && !loading;
  const resolveColor = (colorToken: string) => colorToken.startsWith('{colors.') ? colorToken.slice(8, -1).split('.').reduce((obj: any, key: string) => obj?.[key] ?? colorToken, colors) : colorToken;
  const bgColor = isInteractive ? resolveColor(vStyles.bg) : resolveColor(vStyles.bgDisabled);
  const borderColor = resolveColor(vStyles.borderColor); const textColor = isInteractive ? resolveColor(vStyles.textColor) : resolveColor(vStyles.textColorDisabled);
  const buttonStyle: ViewStyle = { height: sStyles.height, paddingHorizontal: sStyles.paddingHorizontal, paddingVertical: sStyles.paddingVertical, borderRadius: sStyles.borderRadius, backgroundColor: bgColor, borderWidth: vStyles.borderColor === 'transparent' ? 0 : 1, borderColor, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', minWidth: iconOnly ? sStyles.height : sStyles.minWidth, width: fullWidth ? '100%' : undefined, opacity: isInteractive ? 1 : 0.6 };
  const shadowKey = isInteractive ? vStyles.shadow : 'none'; const shadowStyle = theme.shadows[shadowKey as keyof typeof theme.shadows]; if (shadowStyle && shadowKey !== 'none') Object.assign(buttonStyle, shadowStyle);
  const contentStyle: ViewStyle = { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: sStyles.iconGap };
  const labelStyle: TextStyle = { fontSize: sStyles.fontSize, fontWeight: theme.typography.fontWeight.bold, color: textColor, fontFamily: theme.typography.fontFamily.primary, letterSpacing: 0.2, textAlign: 'center' };
  const iconContainerStyle: ViewStyle = { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 0 };
  if (iconStyle) { Object.assign(iconContainerStyle, iconStyle); }
  const handlePress = (e: React.BaseSyntheticEvent) => { if (preventDefault) e.preventDefault(); if (isInteractive && onPress) onPress(); };
  const handleLongPress = (e: React.BaseSyntheticEvent) => { if (preventDefault) e.preventDefault(); if (isInteractive && onLongPress) onLongPress(); };
  return <Pressable ref={ref} onPress={handlePress} onLongPress={handleLongPress} disabled={disabled || loading} accessibilityRole="button" accessibilityState={{ disabled: disabled || loading, busy: loading }} accessibilityLabel={accessibilityLabel || (typeof children === 'string' ? children : undefined)} accessibilityHint={accessibilityHint} testID={testID} style={[buttonStyle, style]}><View style={contentStyle}>{loading && !iconOnly && <ActivityIndicator size="small" color={textColor} style={{ marginRight: sStyles.iconGap }} />}{!loading && leftIcon && <View style={iconContainerStyle}>{leftIcon}</View>}{children && !iconOnly && <Text style={[labelStyle, textStyle]}>{loading && loadingText ? loadingText : children}</Text>}{!loading && rightIcon && !iconOnly && <View style={iconContainerStyle}>{rightIcon}</View>}</View></Pressable>;
});
Button.displayName = 'Button';
export default Button;