import cors from 'cors';
import express from 'express';
import helmet from 'helmet';
import { env } from './config/env.js';
import { databaseHealth } from './infrastructure/database.js';
import { authenticationRouter } from './modules/authentication/routes/authentication.routes.js';
import { healthRouter } from './modules/health/health.routes.js';
import { organizationRouter } from './modules/organizations/routes/organization.routes.js';
import { customerRouter } from './modules/customers/routes/customer.routes.js';
import { supplierRouter } from './modules/suppliers/routes/supplier.routes.js';
import { productRouter } from './modules/products/routes/product.routes.js';
import { inventoryRouter } from './modules/inventory/routes/inventory.routes.js';
import { purchaseRequestRouter } from './modules/purchases/routes/purchase-request.routes.js';
import { purchaseOrderRouter } from './modules/purchases/routes/purchase-order.routes.js';
import { salesOrderRouter } from './modules/sales/routes/sales-order.routes.js';
import { journalEntryRouter } from './modules/accounting/routes/journal-entry.routes.js';
import { workflowRouter } from './modules/automation/routes/workflow.routes.js';
import { branchRouter } from './modules/branches/routes/branch.routes.js';
import { catalogRouter } from './modules/catalogs/routes/catalog.routes.js';
import { leadRouter } from './modules/crm/routes/lead.routes.js';
import { opportunityRouter } from './modules/crm/routes/opportunity.routes.js';
import { contactActivityRouter } from './modules/crm/routes/contact-activity.routes.js';
import { shipmentRouter } from './modules/logistics/routes/shipment.routes.js';
import { warehouseRouter } from './modules/warehouses/routes/warehouse.routes.js';
import { creditMemoRouter, customerRefundRouter, invoiceRouter, paymentRouter, supplierInvoiceRouter, supplierPaymentRouter } from './modules/finance/routes/finance.routes.js';
import { dashboardRouter } from './modules/dashboard/routes/dashboard.routes.js';
import { userRouter } from './modules/users/routes/user.routes.js';
import { settingRouter } from './modules/settings/routes/setting.routes.js';
import { taxRouter } from './modules/taxes/routes/tax.routes.js';
import { accountRouter } from './modules/chart-of-accounts/routes/account.routes.js';
import { journalEntryRouter as accountingJournalEntryRouter } from './modules/journal-entries/routes/journal-entry.routes.js';
import { accountsReceivableRouter } from './modules/accounts-receivable/routes/accounts-receivable.routes.js';
import { accountsPayableRouter } from './modules/accounts-payable/routes/accounts-payable.routes.js';
import { bankAccountRouter } from './modules/banking/routes/bank-account.routes.js';
import { budgetRouter } from './modules/budgets/routes/budget.routes.js';
import { bomRouter } from './modules/bills-of-materials/routes/bom.routes.js';
import { productionOrderRouter } from './modules/production-orders/routes/production-order.routes.js';
import { errorHandler, notFoundHandler } from './shared/http.js';
import { requestIdMiddleware } from './shared/request-id.js';

export const app = express();

app.disable('x-powered-by');
app.use(requestIdMiddleware);
app.use(helmet());
const allowedOrigins = new Set(env.CORS_ORIGINS.split(',').map((origin) => origin.trim()).filter(Boolean));
app.use(cors({
  origin: (origin, callback) => {
    callback(null, !origin || allowedOrigins.has(origin));
  },
}));
app.use(express.json({ limit: '1mb' }));

app.use('/health', healthRouter(databaseHealth));
app.use(`${env.API_PREFIX}/health`, healthRouter(databaseHealth));
app.use(`${env.API_PREFIX}/auth`, authenticationRouter);
app.use(`${env.API_PREFIX}/organizations`, organizationRouter);
app.use(`${env.API_PREFIX}/users`, userRouter);
app.use(`${env.API_PREFIX}/customers`, customerRouter);
app.use(`${env.API_PREFIX}/suppliers`, supplierRouter);
app.use(`${env.API_PREFIX}/products`, productRouter);
app.use(`${env.API_PREFIX}/inventory`, inventoryRouter);
app.use(`${env.API_PREFIX}/purchase-requests`, purchaseRequestRouter);
app.use(`${env.API_PREFIX}/purchase-orders`, purchaseOrderRouter);
app.use(`${env.API_PREFIX}/sales-orders`, salesOrderRouter);
app.use(`${env.API_PREFIX}/journal-entries`, journalEntryRouter);
app.use(`${env.API_PREFIX}/workflows`, workflowRouter);
app.use(`${env.API_PREFIX}/branches`, branchRouter);
app.use(`${env.API_PREFIX}/catalogs`, catalogRouter);
app.use(`${env.API_PREFIX}/crm/leads`, leadRouter);
app.use(`${env.API_PREFIX}/crm/opportunities`, opportunityRouter);
app.use(`${env.API_PREFIX}/crm`, contactActivityRouter);
app.use(`${env.API_PREFIX}/shipments`, shipmentRouter);
app.use(`${env.API_PREFIX}/warehouses`, warehouseRouter);
app.use(`${env.API_PREFIX}/invoices`, invoiceRouter);
app.use(`${env.API_PREFIX}/credit-memos`, creditMemoRouter);
app.use(`${env.API_PREFIX}/customer-refunds`, customerRefundRouter);
app.use(`${env.API_PREFIX}/payments`, paymentRouter);
app.use(`${env.API_PREFIX}/supplier-invoices`, supplierInvoiceRouter);
app.use(`${env.API_PREFIX}/supplier-payments`, supplierPaymentRouter);
app.use(`${env.API_PREFIX}/dashboard`, dashboardRouter);
app.use(`${env.API_PREFIX}/settings`, settingRouter);
app.use(`${env.API_PREFIX}/taxes`, taxRouter);
app.use(`${env.API_PREFIX}/chart-of-accounts`, accountRouter);
app.use(`${env.API_PREFIX}/journal-entries`, accountingJournalEntryRouter);
app.use(`${env.API_PREFIX}/accounts-receivable`, accountsReceivableRouter);
app.use(`${env.API_PREFIX}/accounts-payable`, accountsPayableRouter);
app.use(`${env.API_PREFIX}/banking`, bankAccountRouter);
app.use(`${env.API_PREFIX}/budgets`, budgetRouter);
app.use(`${env.API_PREFIX}/bills-of-materials`, bomRouter);
app.use(`${env.API_PREFIX}/production-orders`, productionOrderRouter);
app.use(notFoundHandler);
app.use(errorHandler);
