import cors from 'cors';
import express from 'express';
import helmet from 'helmet';
import { env } from './config/env.js';
import { databaseHealth } from './infrastructure/database.js';
import { authenticationRouter } from './modules/authentication/routes/authentication.routes.js';
import { healthRouter } from './modules/health/health.routes.js';
import { organizationRouter } from './modules/organizations/routes/organization.routes.js';
import { customerRouter } from './modules/customers/routes/customer.routes.js';
import { supplierRouter } from './modules/suppliers/routes/supplier.routes.js';
import { productRouter } from './modules/products/routes/product.routes.js';
import { inventoryRouter } from './modules/inventory/routes/inventory.routes.js';
import { purchaseRequestRouter } from './modules/purchases/routes/purchase-request.routes.js';
import { purchaseOrderRouter } from './modules/purchases/routes/purchase-order.routes.js';
import { salesOrderRouter } from './modules/sales/routes/sales-order.routes.js';
import { journalEntryRouter } from './modules/accounting/routes/journal-entry.routes.js';
import { workflowRouter } from './modules/automation/routes/workflow.routes.js';
import { branchRouter } from './modules/branches/routes/branch.routes.js';
import { catalogRouter } from './modules/catalogs/routes/catalog.routes.js';
import { leadRouter } from './modules/crm/routes/lead.routes.js';
import { opportunityRouter } from './modules/crm/routes/opportunity.routes.js';
import { contactActivityRouter } from './modules/crm/routes/contact-activity.routes.js';
import { shipmentRouter } from './modules/logistics/routes/shipment.routes.js';
import { warehouseRouter } from './modules/warehouses/routes/warehouse.routes.js';
import { invoiceRouter, paymentRouter } from './modules/finance/routes/finance.routes.js';
import { errorHandler, notFoundHandler } from './shared/http.js';
import { requestIdMiddleware } from './shared/request-id.js';

export const app = express();

app.disable('x-powered-by');
app.use(requestIdMiddleware);
app.use(helmet());
app.use(cors());
app.use(express.json({ limit: '1mb' }));

app.use('/health', healthRouter(databaseHealth));
app.use(`${env.API_PREFIX}/health`, healthRouter(databaseHealth));
app.use(`${env.API_PREFIX}/auth`, authenticationRouter);
app.use(`${env.API_PREFIX}/organizations`, organizationRouter);
app.use(`${env.API_PREFIX}/customers`, customerRouter);
app.use(`${env.API_PREFIX}/suppliers`, supplierRouter);
app.use(`${env.API_PREFIX}/products`, productRouter);
app.use(`${env.API_PREFIX}/inventory`, inventoryRouter);
app.use(`${env.API_PREFIX}/purchase-requests`, purchaseRequestRouter);
app.use(`${env.API_PREFIX}/purchase-orders`, purchaseOrderRouter);
app.use(`${env.API_PREFIX}/sales-orders`, salesOrderRouter);
app.use(`${env.API_PREFIX}/journal-entries`, journalEntryRouter);
app.use(`${env.API_PREFIX}/workflows`, workflowRouter);
app.use(`${env.API_PREFIX}/branches`, branchRouter);
app.use(`${env.API_PREFIX}/catalogs`, catalogRouter);
app.use(`${env.API_PREFIX}/crm/leads`, leadRouter);
app.use(`${env.API_PREFIX}/crm/opportunities`, opportunityRouter);
app.use(`${env.API_PREFIX}/crm`, contactActivityRouter);
app.use(`${env.API_PREFIX}/shipments`, shipmentRouter);
app.use(`${env.API_PREFIX}/warehouses`, warehouseRouter);
app.use(`${env.API_PREFIX}/invoices`, invoiceRouter);
app.use(`${env.API_PREFIX}/payments`, paymentRouter);
app.use(notFoundHandler);
app.use(errorHandler);
